import os

from dotenv import load_dotenv

load_dotenv()

TEST_DB_USER_PASSWORD = os.getenv("TEST_DB_USER_PASSWORD")
JWT_SECRET = os.getenv("JWT_SECRET")
VERIFICATION_TOKEN_SECRET = os.getenv("VERIFICATION_TOKEN_SECRET")
TEST_BACKEND_USER_USERNAME: str = os.getenv('TEST_BACKEND_USER_USERNAME')
TEST_BACKEND_USER_PASSWORD: str = os.getenv("TEST_BACKEND_USER_PASSWORD")