name: Build

on:
  push:
    branches:
      - cd-test

jobs:
  build:
    runs-on: local-runner
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: user/app:latest