
on:
  push:
    branches:
      - cd-test1
      - main
  workflow_dispatch:

jobs:
  run_docker_container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t alarm-bot-server .

      - name: Run Docker container
        env:
          APP_HOST: ${{ secrets.APP_HOST }}
          APP_PORT: ${{ secrets.APP_PORT }}
          DB_USER_PASSWORD: ${{ secrets.DB_USER_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          VERIFICATION_TOKEN_SECRET: ${{ secrets.VERIFICATION_TOKEN_SECRET }}
          TEST_BACKEND_USER_USERNAME: ${{ secrets.TEST_BACKEND_USER_USERNAME }}
          TEST_BACKEND_USER_PASSWORD: ${{ secrets.TEST_BACKEND_USER_PASSWORD }}
        run: docker run --env APP_HOST=$APP_HOST --env APP_PORT=$APP_PORT --env DB_USER_PASSWORD=$DB_USER_PASSWORD --env JWT_SECRET=$JWT_SECRET --env VERIFICATION_TOKEN_SECRET=$VERIFICATION_TOKEN_SECRET --env TEST_BACKEND_USER_USERNAME=$TEST_BACKEND_USER_USERNAME --env TEST_BACKEND_USER_PASSWORD=$TEST_BACKEND_USER_PASSWORD alarm-bot-server
