on:
  # Triggers the workflow on pull request events
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs
jobs:
  # Single job called "routers_tests"
  routers_tests:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t alarm-bot-server .

      - name: Run tests in Docker container
        env:
          APP_HOST: ${{ secrets.APP_HOST }}
          APP_PORT: ${{ secrets.APP_PORT }}
          DB_USER_PASSWORD: ${{ secrets.DB_USER_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          VERIFICATION_TOKEN_SECRET: ${{ secrets.VERIFICATION_TOKEN_SECRET }}
          TEST_BACKEND_USER_USERNAME: ${{ secrets.TEST_BACKEND_USER_USERNAME }}
          TEST_BACKEND_USER_PASSWORD: ${{ secrets.TEST_BACKEND_USER_PASSWORD }}
        run: docker run --env APP_HOST=$APP_HOST --env APP_PORT=$APP_PORT --env DB_USER_PASSWORD=$DB_USER_PASSWORD --env JWT_SECRET=$JWT_SECRET --env VERIFICATION_TOKEN_SECRET=$VERIFICATION_TOKEN_SECRET --env TEST_BACKEND_USER_USERNAME=$TEST_BACKEND_USER_USERNAME --env TEST_BACKEND_USER_PASSWORD=$TEST_BACKEND_USER_PASSWORD alarm_bot_server pytest -vv -s